### ISSUE TITLE
Cannot reproduce your results

### ISSUE THREAD

**Issue by fabvio** [shahabty/PSPNet-Pytorch#1]
Hi,
I downloaded the pretrained caffemodel and put it in the correct directory, I have no errors at all, but the main script gives me IoU of 8%. Do you have any ideas why? I'm using pytorch 0.4.1.

**Comment by shahabty** [comment]
Hello @fabvio, have you modified or changed the code in this repo? or do you get 8% MIoU by only using pre-trained weights with your own code?

**Comment by fabvio** [comment]
No, I haven't changed anything, just clone the repo, followed your instructions, and ran the script.

**Comment by shahabty** [comment]
@fabvio I have re-evaluate it. Here is the output: 
[acc 0.95196], [acc_cls 0.83369], [mean_iu 0.75547], [fwavacc 0.91172]
Also I have found this in the official repo of PSPNET:
PSPNet101 on cityscapes valset (mIoU/pAcc): 79.70/96.38 (ss) and 80.91/96.59 (ms)
