### ISSUE TITLE
val set result

### ISSUE THREAD

**Issue by sanweiliti** [shahabty/PSPNet-Pytorch#2]
Hi, 
did you try the pspnet from repo pytorch-semseg (https://github.com/meetshah1995/pytorch-semseg)? I think the model structure in your code is almost the same as theirs, but their model can only produce mIoU of about 52% on val set, and I cannot find any difference in data processing, do you know why?

**Comment by shahabty** [comment]
Hi @sanweiliti, 
I use caffe pretrained weights from official repo of papnet.

**Comment by sanweiliti** [comment]
Hi @shahabty ,
thanks! I also used the official pretrained weights. I combined with pytorch-semseg's dataloader and your PSP model and still got 53% on val set so I guess the problem lies with the processing. And what is the tile_predict() function in pspnet.py for?

**Comment by shahabty** [comment]
Could you please share more information about your preprocessing and post processing?

**Comment by sanweiliti** [comment]
It works now! Turns out I forgot to sustract the pascal mean from the input image realier.
