### ISSUE TITLE
Use custom dataset

### ISSUE THREAD

**Issue by prraoo** [shahabty/PSPNet-Pytorch#3]
@shahabty thank you for the code, I works fine :) I could get good results with the cityscapes dataset. However If I have to use a custom dataset, how can I do that?

**Comment by shahabty** [comment]
@raoanonymous you’re welcome.
Is it a private dataset or another public dataset?

**Comment by prraoo** [comment]
@shahabty it is a private dataset, just an informal collection of images similar to the Cityscape data. Fortunately, I could manage to run evaluations of my data by changing the strings in the "make_dataset" function. 
Also, it would be nice to have a mapping between the generated images and ground truth images, had a tough time find the ground truth images for the predictions. I did it by an adding extra member in dataloader having image filename.
