### ISSUE TITLE
About mean_std value

### ISSUE THREAD

**Issue by kangpl** [shahabty/PSPNet-Pytorch#5]
Hi,
If I want to finetune this PSPNet, How should I set the transform, especially the mean std value?
Thanks

**Comment by shahabty** [comment]
> Hi,
> If I want to finetune this PSPNet, How should I set the transform, especially the mean std value?
> Thanks

Hello,
Please follow PSPNet paper for the transformation required during training. You may follow the same mean, std values in this code.
